### ISSUE TITLE
Feature: Listen only on specific IP address

### ISSUE THREAD

**Issue by levicki** [PocketRelay/ServerRust#56]
## Is your feature request related to a problem? Please describe.
Currently PocketRelay server listens on 0.0.0.0 (wildcard IP).

## Describe the solution you'd like
It would be nice to be able to bind it to a specific IP address. Therefore, I propose adding `ip` (or `host`) option in `config.json` file in addition to the `port` which is already present.

## Describe alternatives you've considered
N/A

## Additional context
Security hardening.

**Comment by jacobtread** [comment]
Change added and merged into dev branch, will be available in the next server release
